# Generated by Django 5.2 on 2025-04-26 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coordinates', '0001_initial'),
        ('photo', '0001_initial'),
        ('tourist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pereval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beauty_title', models.CharField(blank=True, max_length=255, verbose_name='Сокращенное название')),
                ('title', models.CharField(max_length=255, verbose_name='Полное название')),
                ('other_titles', models.CharField(blank=True, max_length=255, verbose_name='Альтернативное название')),
                ('connect', models.CharField(blank=True, max_length=255, verbose_name='Соединяет')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('level', models.CharField(choices=[('winter', 'Зима'), ('summer', 'Лето'), ('autumn', 'Осень'), ('spring', 'Весна')], default='summer', max_length=10, verbose_name='Уровень сложности')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('pending', 'В работе'), ('accepted', 'Принят'), ('rejected', 'Отклонен')], default='new', max_length=10, verbose_name='Статус')),
                ('area', models.CharField(choices=[('Planet Earth', 'Планета Земля'), ('Pamiro-Alai', 'Памиро-Алай'), ('Altay', 'Алтай'), ('Nothern-Chuiskiy Ridge', 'Северо-Чуйский хребет'), ('Southern-Chuiskiy Ridge', 'Южно-Чуйский хребет'), ('Katun Ridge', 'Катунский хребет'), ('Fansky mountains', 'Фанские горы'), ('Gussarskiy Ridge(west from The Anzob Pass)', 'Гиссарский хребет (участок западнее перевала Анзоб)'), ('Matchinskiy mountain knot', 'Матчинский горный узел'), ('Takali mountain knot-Turkestan ridge', 'Горный узел Такали-Туркестанский хребет'), ('High Alay', 'Высокий Алай'), ('Kichik-Alay and Eastern Alay', 'Кичик-Алай и Восточный Алай'), ('Aladaglar', 'Аладаглар'), ('Tavr', 'Тавр'), ('Sayan mountains', 'Саяны'), ('Lisvyaga Ridge', 'Хребет Листвяга'), ('Ivanovsky Ridge', 'Ивановский хребет'), ('Mungun-Taiga massif', 'Массив Мунгун-Тайга'), ('Tsagan-Shibetu Ridge', 'Хребет Цаган-Шибэту'), ('Chikhachev Ridge (Sailugem)', 'Хребет Чихачева (Сайлюгем)'), ('Shapshalsky Ridge', 'Шапшальский хребет'), ('Southern Altai Ridge', 'Хребет Южный Алтай'), ('Mongolian Altai Ridge', 'Хребет Монгольский Алтай'), ('Western Sayan', 'Западный Саян'), ('Eastern Sayan', 'Восточный Саян'), ('Kuznetsky Alatau', 'Кузнецкий Алатау'), ('Kurai ridge', 'Курайский хребет')], default='Planet Earth', max_length=100, verbose_name='Область')),
                ('coords', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='coordinates.coords', verbose_name='Координаты')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='photo.image')),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tourist', to='tourist.tourist', verbose_name='Турист')),
            ],
            options={
                'verbose_name': 'Перевал',
                'verbose_name_plural': 'Перевалы',
            },
        ),
    ]
