# Generated by Django 5.2 on 2025-04-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pereval',
            name='area',
            field=models.CharField(choices=[('Planet Earth', 'Планета Земля'), ('Pamiro-Alai', 'Памиро-Алай'), ('Altay', 'Алтай'), ('Nothern-Chuiskiy Ridge', 'Северо-Чуйский хребет'), ('Southern-Chuiskiy Ridge', 'Южно-Чуйский хребет'), ('Katun Ridge', 'Катунский хребет'), ('Fansky mountains', 'Фанские горы'), ('Gussarskiy Ridge(west from The Anzob Pass)', 'Гиссарский хребет (участок западнее перевала Анзоб)'), ('Matchinskiy mountain knot', 'Матчинский горный узел'), ('Takali mountain knot-Turkestan ridge', 'Горный узел Такали-Туркестанский хребет'), ('High Alay', 'Высокий Алай'), ('Kichik-Alay and Eastern Alay', 'Кичик-Алай и Восточный Алай'), ('Aladaglar', 'Аладаглар'), ('Tavr', 'Тавр'), ('Sayan mountains', 'Саяны'), ('Listvyaga Ridge', 'Хребет Листвяга'), ('Ivanovsky Ridge', 'Ивановский хребет'), ('Mungun-Taiga massif', 'Массив Мунгун-Тайга'), ('Tsagan-Shibetu Ridge', 'Хребет Цаган-Шибэту'), ('Chikhachev Ridge (Sailugem)', 'Хребет Чихачева (Сайлюгем)'), ('Shapshalsky Ridge', 'Шапшальский хребет'), ('Southern Altai Ridge', 'Хребет Южный Алтай'), ('Mongolian Altai Ridge', 'Хребет Монгольский Алтай'), ('Western Sayan', 'Западный Саян'), ('Eastern Sayan', 'Восточный Саян'), ('Kuznetsky Alatau', 'Кузнецкий Алатау'), ('Kurai ridge', 'Курайский хребет')], default='Planet Earth', max_length=100, verbose_name='Область'),
        ),
    ]
