# Generated by Django 5.2 on 2025-04-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0002_alter_pereval_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Согласие с условиями',
                'verbose_name_plural': 'Согласия с условиями',
            },
        ),
    ]
