# Generated by Django 5.2 on 2025-04-28 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0003_termsagreement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('moderator', models.TextField(null=True, verbose_name='Модератор')),
                ('pereval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_comments', to='pereval.pereval')),
            ],
            options={
                'verbose_name': 'Комментарий модератора',
                'verbose_name_plural': 'Комментарии модераторов',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('status_change', 'Изменение статуса'), ('comment', 'Комментарий модератора')], max_length=20, verbose_name='Тип уведомления')),
                ('message', models.TextField(verbose_name='Текст уведомления')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлено')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('pereval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='pereval.pereval')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created'],
            },
        ),
    ]
