# Generated by Django 5.2 on 2025-04-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tourist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, verbose_name='Электронная почта')),
                ('fam', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('otc', models.CharField(max_length=255, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('type', models.CharField(choices=[('walking', 'пешком'), ('skiing', 'лыжи'), ('catamaran', 'катамаран'), ('kayak', 'байдарка'), ('ferry', 'пaром'), ('rafting', 'сплав'), ('cycling', 'велосипед'), ('auto', 'автомобиль'), ('moto', 'мотоцикл'), ('sail', 'парус'), ('horseback', 'верхом')], default='auto', max_length=20, verbose_name='Вид туризма')),
            ],
            options={
                'verbose_name': 'Турист',
                'verbose_name_plural': 'Туристы',
            },
        ),
    ]
